export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";

export const CART_PRICE_INCREASE = "CART_PRICE_INCREASE";
export const CHANGE_PRODUCT_PRICE="CHANGE_PRODUCT_PRICE";

export const INCREASE_PRODUCT="INCREASE_PRODUCT";
